export const RouterPaths = {
  MAIN: "/",
  LOGIN: "/login",
  REGISTRATION: "/register",
  PROFILE: "/profile",
  PROFILE_ORDERS: "orders",
  PROFILE_LOGOUT: "logout",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  INGREDIENTS: "/ingredients/:id",
  FEED: "/feed",
  FEED_ORDER: "/feed/:id",
  OWN_ORDERS: "orders",
  OWN_ORDER: "orders/:id",
  NOTFOUND: "*",
  ERROR: "/error",
} as const;
